language: node_js
node_js:
  - "node"
notifications:
  email: false
deploy:
  provider: firebase
  token:
    secure: "1//06hGDfW1glSTfCgYIARAAGAYSNwF-L9Ir9mH_TJZjOiWRoZq2QKnx0_IQ6W7prMXic3MbbW82_KMGWOoj1RC3z53kp_YfIfMl_Mg"
